// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snejpdsldulrnkccfaex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZWpwZHNsZHVscm5rY2NmYWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4OTY3NjIsImV4cCI6MjA3MjQ3Mjc2Mn0.-iIRysf-1CiBuO4hNfeHXKr0TAhVxi6xMU8L5Dm5fp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});